Controllers/District/DistrictReportController.cs
using APATools.Context;
using APATools.Models.ReportModels;
using Microsoft.AspNetCore.Mvc;

namespace APATools.Controllers.District
{
    public class DistrictReportController : Controller
    {
        private readonly ILogger<DistrictReportController> _logger;
        private readonly APAToolsContext _context;
        public DistrictReportController(ILogger<DistrictReportController> logger, APAToolsContext context)
        {
            _context = context;
            _logger = logger;
        }
        public IActionResult APA_MC_1_DCU()
        {
            if (HttpContext.Session.GetString("isLoggedIn") == "DistrictAdmin")
            {
                var accessID = Convert.ToInt32(HttpContext.Session.GetString("UserAccessID"));
                var data = from ap in _context.A_APA_MC_1s
                           join loc in _context.view_alllocations on ap.GPCode equals loc.GPCode
                           join fin in _context.mst_FinancialYears on ap.FYCode equals fin.FYCode
                           where loc.DistrictCode == accessID
                           select new APA_MC_1_Report
                           {
                               ID = ap.ID,
                               GPCode = ap.GPCode,
                               GPName = loc.GPName,
                               BlockName = loc.BlockName,
                               SubDivisionName = loc.SubDivisionName,
                               DistrictName = loc.DistrictName,
                               FYCode = ap.FYCode,
                               FYName = fin.FYName,
                               TotalNoofMember = ap.TotalNoofMember,
                               NoofMemberAttended = ap.NoofMemberAttended,
                               PlanApprovalDate = ap.PlanApprovalDate,
                               SingleAgendaMeeting = ap.SingleAgendaMeeting,
                               EvidenceofPlanApprovalResolution = ap.EvidenceofPlanApprovalResolution,
                               EvidenceofPlanApprovalResolution_path = ap.EvidenceofPlanApprovalResolution_path,
                               TotalMembersDeclaration_pdf = ap.TotalMembersDeclaration_pdf,
                               TotalMembersDeclaration_pdf_path = ap.TotalMembersDeclaration_pdf_path,
                               TotalMembersDeclaration_excel = ap.TotalMembersDeclaration_excel,
                               TotalMembersDeclaration_excel_path = ap.TotalMembersDeclaration_excel_path,
                               ActiveStatus = ap.ActiveStatus
                           };
                return View(data);
            }
            else
            {
                TempData["Failed"] = "You are not a valid user";
                return RedirectToAction("Login", "User");
            }
        }
        public IActionResult APA_MC_2_DCU()
        {
            if (HttpContext.Session.GetString("isLoggedIn") == "DistrictAdmin")
            {
                var accessID = Convert.ToInt32(HttpContext.Session.GetString("UserAccessID"));
                var data = from ap in _context.A_APA_MC_2s
                           join loc in _context.view_alllocations on ap.GPCode equals loc.GPCode
                           join fin in _context.mst_FinancialYears on ap.FYCode equals fin.FYCode
                           where loc.DistrictCode == accessID
                           select new APA_MC_2_Report
                           {
                               ID = ap.ID,
                               GPCode = ap.GPCode,
                               GPName = loc.GPName,
                               BlockName = loc.BlockName,
                               SubDivisionName = loc.SubDivisionName,
                               DistrictName = loc.DistrictName,
                               FYCode = ap.FYCode,
                               FYName = fin.FYName,
                               DeclarationStatusPhysicalCompletedActivities = ap.DeclarationStatusPhysicalCompletedActivities,
                               DeclarationStatusPhysicalCompletedActivities_Path = ap.DeclarationStatusPhysicalCompletedActivities_Path,
                               NoofPhysicallyCompletedActivities = ap.NoofPhysicallyCompletedActivities,
                               NoofIssuedWorkOrder = ap.NoofIssuedWorkOrder,
                               DeclarationPlan_Implementation = ap.DeclarationPlan_Implementation,
                               DeclarationPlan_Implementation_Path = ap.DeclarationPlan_Implementation_Path,
                               EvidenceofCompletedActivity = ap.EvidenceofCompletedActivity,
                               EvidenceofCompletedActivity_Path = ap.EvidenceofCompletedActivity_Path,
                               ActiveStatus = ap.ActiveStatus
                           };
                return View(data);
            }
            else
            {
                TempData["Failed"] = "You are not a valid user";
                return RedirectToAction("Login", "User");
            }
        }
        public IActionResult APA_MC_5_DCU()
        {
            if (HttpContext.Session.GetString("isLoggedIn") == "DistrictAdmin")
            {
                var accessID = Convert.ToInt32(HttpContext.Session.GetString("UserAccessID"));
                var data = from ap in _context.A_APA_MC_5s
                           join loc in _context.view_alllocations on ap.GPCode equals loc.GPCode
                           join fin in _context.mst_FinancialYears on ap.FYCode equals fin.FYCode
                           where loc.DistrictCode == accessID
                           select new APA_MC_5_Report
                           {
                               ID = ap.ID,
                               GPCode = ap.GPCode,
                               GPName = loc.GPName,
                               BlockName = loc.BlockName,
                               SubDivisionName = loc.SubDivisionName,
                               DistrictName = loc.DistrictName,
                               FYCode = ap.FYCode,
                               FYName = fin.FYName,
                               AuditOpinion = ap.AuditOpinion,
                               AuditCertificate = ap.AuditCertificate,
                               AuditCertificate_Path = ap.AuditCertificate_Path,
                               ActiveStatus = ap.ActiveStatus
                           };
                return View(data);
            }
            else
            {
                TempData["Failed"] = "You are not a valid user";
                return RedirectToAction("Login", "User");
            }
        }
        public IActionResult APA_MC_6_DCU()
        {
            if (HttpContext.Session.GetString("isLoggedIn") == "DistrictAdmin")
            {
                var accessID = Convert.ToInt32(HttpContext.Session.GetString("UserAccessID"));
                var data = from ap in _context.A_APA_MC_6s
                           join loc in _context.view_alllocations on ap.GPCode equals loc.GPCode
                           join fin in _context.mst_FinancialYears on ap.FYCode equals fin.FYCode
                           where loc.DistrictCode == accessID
                           select new APA_MC_6_Report
                           {
                               ID = ap.ID,
                               GPCode = ap.GPCode,
                               GPName = loc.GPName,
                               BlockName = loc.BlockName,
                               SubDivisionName = loc.SubDivisionName,
                               DistrictName = loc.DistrictName,
                               FYCode = ap.FYCode,
                               FYName = fin.FYName,
                               TotalTaxinINR_2324 = ap.TotalTaxinINR_2324,
                               TotalNonTaxinINR_2324 = ap.TotalNonTaxinINR_2324,
                               TotalOSRinINR_2324 = ap.TotalOSRinINR_2324,
                               OSRDeductionAmountinINR_2324 = ap.OSRDeductionAmountinINR_2324,
                               TotalTaxinINR_2425 = ap.TotalTaxinINR_2425,
                               TotalNonTaxinINR_2425 = ap.TotalNonTaxinINR_2425,
                               TotalOSRinINR_2425 = ap.TotalOSRinINR_2425,
                               OSRDeductionAmountinINR_2425 = ap.OSRDeductionAmountinINR_2425,
                               OSRDataUpload = ap.OSRDataUpload,
                               OSRDataUpload_path = ap.OSRDataUpload_path,
                               CCERUpload_2024_2025 = ap.CCERUpload_2024_2025,
                               CCERUpload_2024_2025_path = ap.CCERUpload_2024_2025_path,
                               ActiveStatus = ap.ActiveStatus
                           };
                return View(data);
            }
            else
            {
                TempData["Failed"] = "You are not a valid user";
                return RedirectToAction("Login", "User");
            }
        }
        public IActionResult APA_TE_1_DCU()
        {
            if (HttpContext.Session.GetString("isLoggedIn") == "DistrictAdmin")
            {
                var accessID = Convert.ToInt32(HttpContext.Session.GetString("UserAccessID"));
                var data = from ap in _context.A_APA_TE_1s
                           join loc in _context.view_alllocations on ap.GPCode equals loc.GPCode
                           join fin in _context.mst_FinancialYears on ap.FYCode equals fin.FYCode
                           where loc.DistrictCode == accessID
                           select new APA_TE_1_Report
                           {
                               ID = ap.ID,
                               GPCode = ap.GPCode,
                               GPName = loc.GPName,
                               BlockName = loc.BlockName,
                               SubDivisionName = loc.SubDivisionName,

Views/DistrictReport/APA_MC_1_DCU.cshtml
@model IEnumerable<APATools.Models.ReportModels.APA_MC_1_Report>
@{
    ViewBag.Title = "Report of APA-MC-1";
}

<div class="page-title">
    <div class="title_left">
        <h3>Welcome to the Report of APA-MC-1</h3>
    </div>
    <div class="title_right">
        <div class="col-md-5 col-sm-5   form-group pull-right top_search">
            <div class="input-group">
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
            <div class="x_title">

                <h2>
                    Home of @if (Context.Session.GetString("UserInfo") != null)
                    {
                        <small>@Context.Session.GetString("UserInfo")</small>
                    }
                </h2>
                <div class="clearfix"></div>
            </div>
            @if (TempData["Failed"] != null)
            {
                <div class="x_content">
                    <div class="alert alert-danger">
                        @TempData["Failed"]
                    </div>
                </div>
            }
            @if (TempData["Success"] != null)
            {
                <div class="x_content">
                    <div class="alert alert-success">
                        @TempData["Success"]
                    </div>
                </div>
            }
            <div class="x_content">


                <div class="row">
                    <table id="reportid" style="width:100%" class="display table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th class="col-form-label">District Name</th>
                                <th class="col-form-label">SubDivision Name</th>
                                <th class="col-form-label">Block Name</th>
                                <th class="col-form-label">GP Name</th>
                                <th class="col-form-label">GPCode</th>
                                <th class="col-form-label">Financial Year</th>
                                <th class="col-form-label">Total Number of GP Members (including EX-Officio) in 2023 - 2024</th>
                                <th class="col-form-label">Number of GP Members (including EX-Officio) attended in Special General Body Meeting in 2023 - 2024</th>
                                <th class="col-form-label">Plan Approval Resolution Doc</th>
                                <th class="col-form-label">Total Member's Declaration PDF</th>
                                <th class="col-form-label">Total Member's Declaration Excel</th>
                                <th class="col-form-label">Plan Approval Date</th>
                                <th class="col-form-label">Edit - Update</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    
                                    <td class="col-form-label">@item.DistrictName</td>
                                    <td class="col-form-label">@item.SubDivisionName</td>
                                    <td class="col-form-label">@item.BlockName</td>
                                    <td class="col-form-label">@item.GPName</td>
                                    <td class="col-form-label">@item.GPCode</td>
                                    <td class="col-form-label">@item.FYName</td>
                                    <td class="col-form-label">@item.TotalNoofMember</td>
                                    <td class="col-form-label">@item.NoofMemberAttended</td>
                                    <td class="col-form-label">
                                        <a asp-action="Download" asp-controller="StateDashboard" asp-route-gpcode="@item.GPCode"
                                           asp-route-filename="@item.EvidenceofPlanApprovalResolution_path" class="btn btn-info btn-sm col-form-label">Download</a>
                                    </td>
                                    <td class="col-form-label">
                                        <a asp-action="Download" asp-controller="StateDashboard" asp-route-gpcode="@item.GPCode"
                                           asp-route-filename="@item.TotalMembersDeclaration_pdf_path" class="btn btn-info btn-sm col-form-label">Download</a>

                                    </td>
                                    <td class="col-form-label">
                                        <a asp-action="Download" asp-controller="StateDashboard" asp-route-gpcode="@item.GPCode"
                                           asp-route-filename="@item.TotalMembersDeclaration_excel_path" class="btn btn-info btn-sm col-form-label">Download</a>

                                    </td>
                                    <td class="col-form-label">
                                        @item.PlanApprovalDate
                                    </td>
                                    @if (item.ActiveStatus == 1)
                                    {
                                        <td><a class="btn btn-outline-primary col-form-label" href="@Url.Action("APA_MC_1_DCU_Edit", "DistrictReport", new { id = item.ID })">Allow to Edit Entry</a></td>
                                    }
                                    else if (item.ActiveStatus == 2)
                                    {
                                        <td><a href="#" class="btn btn-warning col-form-label">Already Allowed</a></td>
                                    }
                                    else
                                    {
                                        <td><a class="btn btn-danger col-form-label" href="#">Not Allowed for Edit</a></td>
                                    }
                                </tr>
                            }
                        </tbody>
                    </table>


                </div>
            </div>
        </div>
    </div>
</div>
<style>
    div.dt-container {
        width: 100%;
        margin: 0 auto;
    }

    .dt-end {
        display: table-cell !important;
    }
</style>
@* Datatable Styles *@
<link href="~/css/dataTables.dataTables.css" rel="stylesheet" />
<link href="~/css/buttons.dataTables.css" rel="stylesheet" />
<link href="~/css/fixedColumns.dataTables.css" rel="stylesheet" />
@section Scripts {
    <script type="text/javascript" src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/3.0.2/js/dataTables.buttons.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.dataTables.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.print.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#reportid').DataTable({
                paging: false,
                scrollCollapse: true,
                scrollY: '50vh',
                "lengthMenu": [20, 40, 60, 80, 100],
                fixedColumns: {
                    start: 2,
                    end: 2
                },
                layout: {
                    topStart: {
                        buttons: [{
                    extend: 'excelHtml5',
                    title: 'Data export' + "@DateTime.Now"
                }]
                    },
                    bottomStart: {
                        "pageLength": 20,
                    },
                    bottomEnd: {
                        paging: {
                            firstLast: false
                        }
                    },
                }
            });
        });
    </script>
}

Views/DistrictReport/APA_MC_2_DCU.cshtml
@model IEnumerable<APATools.Models.ReportModels.APA_MC_2_Report>
@{
    ViewBag.Title = "Report of APA-MC-2";
}
<div class="page-title">
    <div class="title_left">
        <h3>Welcome to the Report of APA-MC-2</h3>
    </div>
    <div class="title_right">
        <div class="col-md-5 col-sm-5   form-group pull-right top_search">
            <div class="input-group">
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>
                    Home of @if (Context.Session.GetString("UserInfo") != null)
                    {
                        <small>@Context.Session.GetString("UserInfo")</small>
                    }
                </h2>
                <div class="clearfix"></div>
            </div>
            @if (TempData["Failed"] != null)
            {
                <div class="x_content">
                    <div class="alert alert-danger">
                        @TempData["Failed"]
                    </div>
                </div>
            }
            @if (TempData["Success"] != null)
            {
                <div class="x_content">
                    <div class="alert alert-success">
                        @TempData["Success"]
                    </div>
                </div>
            }
            <div class="x_content">

                <div class="row">
                    <table id="reportid" style="width:100%" class="display table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th class="col-form-label">District Name</th>
                                <th class="col-form-label">SubDivision Name</th>
                                <th class="col-form-label">Block Name</th>
                                <th class="col-form-label">GP Name</th>
                                <th class="col-form-label">GPCode</th>
                                <th>Financial Year</th>
                                <th>Nos. of Issued Work Order</th>
                                <th>Nos. of Physically Completed Activities</th>
                                <th>Declaration on Status of Physically Completed Activites (April 2023 - June 2024)</th>
                                <th>Template on Status of Physically Completed Actvities</th>
                                <th>Evidence of Completion (Completion Certificates)</th>
                                <th>Edit - Update</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td class="col-form-label">@item.DistrictName</td>
                                    <td class="col-form-label">@item.SubDivisionName</td>
                                    <td class="col-form-label">@item.BlockName</td>
                                    <td class="col-form-label">@item.GPName</td>
                                    <td class="col-form-label">@item.GPCode</td>
                                    <td class="col-form-label">@item.FYName</td>
                                    <td class="col-form-label">@item.NoofIssuedWorkOrder</td>
                                    <td class="col-form-label">@item.NoofPhysicallyCompletedActivities</td>
                                    <td class="col-form-label">
                                        <a asp-action="Download" asp-controller="StateDashboard" asp-route-gpcode="@item.GPCode"
                                           asp-route-filename="@item.DeclarationStatusPhysicalCompletedActivities_Path" class="btn btn-info btn-sm col-form-label">Download</a>

                                    </td>
                                    <td class="col-form-label">
                                        <a asp-action="Download" asp-controller="StateDashboard" asp-route-gpcode="@item.GPCode"
                                           asp-route-filename="@item.DeclarationPlan_Implementation_Path" class="btn btn-info btn-sm col-form-label">Download</a>
                                    </td>
                                    <td class="col-form-label">
                                        <a asp-action="Download" asp-controller="StateDashboard" asp-route-gpcode="@item.GPCode"
                                           asp-route-filename="@item.EvidenceofCompletedActivity_Path" class="btn btn-info btn-sm col-form-label">Download</a>
                                    </td>
                                    @if (item.ActiveStatus == 1)
                                    {
                                        <td><a class="btn btn-outline-primary col-form-label" href="@Url.Action("APA_MC_2_DCU_Edit", "DistrictReport", new { id = item.ID })">Allow to Edit Entry</a></td>
                                    }
                                    else if (item.ActiveStatus == 2)
                                    {
                                        <td><a href="#" class="btn btn-warning col-form-label">Already Allowed</a></td>
                                    }
                                    else
                                    {
                                        <td><a class="btn btn-danger col-form-label" href="#">Not Allowed for Edit</a></td>
                                    }
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    div.dt-container {
        width: 100%;
        margin: 0 auto;
    }

    .dt-end {
        display: table-cell !important;
    }
</style>
@* Datatable Styles *@
<link href="~/css/dataTables.dataTables.css" rel="stylesheet" />
<link href="~/css/buttons.dataTables.css" rel="stylesheet" />
<link href="~/css/fixedColumns.dataTables.css" rel="stylesheet" />
@section Scripts {
    <script type="text/javascript" src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/3.0.2/js/dataTables.buttons.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.dataTables.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.print.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#reportid').DataTable({
                paging: false,
                scrollCollapse: true,
                scrollY: '50vh',
                "lengthMenu": [20, 40, 60, 80, 100],
                fixedColumns: {
                    start: 2,
                    end: 2
                },
                layout: {
                    topStart: {
                        buttons: [{
                    extend: 'excelHtml5',
                    title: 'Data export' + "@DateTime.Now"
                }]
                    },
                    bottomStart: {
                        "pageLength": 20,
                    },
                    bottomEnd: {
                        paging: {
                            firstLast: false
                        }
                    },
                }
            });
        });
    </script>
}