Controllers/GP/GPEditDashboardController.cs
using APATools.Context;
using APATools.Models;
using APATools.OldContext;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace APATools.Controllers.GP
{
    public class GPEditDashboardController : Controller
    {
        private readonly ILogger<GPEditDashboardController> _logger;
        private readonly APAToolsContext _context;
        private readonly GPIMSContext _gpimsContext;
        private readonly IWebHostEnvironment _environment;
        public GPEditDashboardController(ILogger<GPEditDashboardController> logger, APAToolsContext context, GPIMSContext gPIMSContext, IWebHostEnvironment environment)
        {
            _context = context;
            _logger = logger;
            _environment = environment;
            _gpimsContext = gPIMSContext;
        }
        private bool RemoveFileFromServer(string path)
        {
            string fullPath = Path.Combine(_environment.WebRootPath, "storages", path);
            if (!System.IO.File.Exists(fullPath)) return false;

            try //Maybe error could happen like Access denied or Presses Already User used
            {
                System.IO.File.Delete(fullPath);
                return true;
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.Message);
            }
            return false;
        }
        public async Task<IActionResult> APA_MC_1_Edit(long id)
        {
            if (HttpContext.Session.GetString("isLoggedIn") == "GPAdmin")
            {
                var data = await _context.A_APA_MC_1s.FindAsync(id);
                if (data != null)
                {
                    var fin = _context.mst_FinancialYears.Where(q => q.FYCode == data.FYCode).FirstOrDefault();
                    ViewBag.FYName = fin.FYName;
                    return View(data);
                }
                else
                {
                    ViewBag.Failed = "Data of the GP not found!";
                    return RedirectToAction("APA_MC_1_Edit", "GPReportDahboard");
                }
            }
            else
            {
                TempData["Failed"] = "Your are not allowed";
                return RedirectToAction("Login", "User");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> APA_MC_1_Edit(A_APA_MC_1 result, IFormFile EvidenceofPlanApprovalResolution, IFormFile TotalMembersDeclaration_pdf, IFormFile TotalMembersDeclaration_excel)
        {
            var fycode = Convert.ToInt32(result.FYCode);
            var gpCode = Convert.ToInt32(result.GPCode);
            int MaxContentLength = 1024 * 1024 * 6;
            var data = _context.A_APA_MC_1s.Where(q => q.GPCode == gpCode).FirstOrDefault();
            if (data != null && EvidenceofPlanApprovalResolution != null && TotalMembersDeclaration_excel != null && TotalMembersDeclaration_pdf != null)
            {
                if (EvidenceofPlanApprovalResolution.Length > MaxContentLength && TotalMembersDeclaration_pdf.Length > MaxContentLength && TotalMembersDeclaration_excel.Length > MaxContentLength)
                {
                    ModelState.AddModelError("EvidenceofPlanApprovalResolution & TotalMembersDeclaration", "File size is big.");
                    TempData["Failed"] = "Your Report could not uploaded! File size is larger than given side.";
                    return View(result);
                }
                else
                {
                    var finData = _context.mst_FinancialYears.Where(q => q.FYCode.Equals(fycode)).FirstOrDefault();
                    var loc = _context.view_alllocations.Where(q => q.GPCode.Equals(gpCode)).FirstOrDefault();

                    var allowedExtensions = new[] { ".pdf", ".jpg", ".png" };

                    var fileNameEvidenceofPlanApprovalResolution = gpCode.ToString() + "-" + "epar" + "-" + DateTime.Now.ToString("yyyyMMddHHmmss");
                    var fileNameTotalMembersDeclaration_pdf = gpCode.ToString() + "-" + "tmd" + "-" + DateTime.Now.ToString("yyyyMMddHHmmss");
                    var fileNameTotalMembersDeclaration_excel = gpCode.ToString() + "-" + "tmd_excel" + "-" + DateTime.Now.ToString("yyyyMMddHHmmss");

                    var extensionEvidenceofPlanApprovalResolution = Path.GetExtension(EvidenceofPlanApprovalResolution.FileName);
                    var extensionTotalMembersDeclaration_pdf = Path.GetExtension(TotalMembersDeclaration_pdf.FileName);
                    var extensionTotalMembersDeclaration_excel = Path.GetExtension(TotalMembersDeclaration_excel.FileName);
                    if (extensionEvidenceofPlanApprovalResolution != ".pdf" && extensionTotalMembersDeclaration_pdf != ".pdf" && extensionTotalMembersDeclaration_excel != ".xlsx")
                    {
                        ModelState.AddModelError("EvidenceofPlanApprovalResolution & TotalMembersDeclaration", "Unsupported file type.");
                        TempData["Failed"] = "Your Report could not uploaded! Unsupported file type.";
                        return View(result);
                    }
                    else
                    {
                        var path1 = data.EvidenceofPlanApprovalResolution_path;
                        var path2 = data.TotalMembersDeclaration_pdf_path;
                        var path3 = data.TotalMembersDeclaration_excel_path;
                        RemoveFileFromServer(path1);
                        RemoveFileFromServer(path2);
                        RemoveFileFromServer(path3);
                        string uploadPathTotalMembersDeclaration_pdf = Path.Combine(_environment.WebRootPath, "storages/apa_mc_1/TMD");

                        string filePathTotalMembersDeclaration_pdf = Path.Combine(uploadPathTotalMembersDeclaration_pdf,
                            fileNameTotalMembersDeclaration_pdf + extensionTotalMembersDeclaration_pdf);
                        //Using Buffering
                        using (var stream = System.IO.File.Create(filePathTotalMembersDeclaration_pdf))
                        {
                            // The file is saved in a buffer before being processed
                            await TotalMembersDeclaration_pdf.CopyToAsync(stream);
                        }
                        string uploadPathTotalMembersDeclaration_excel = Path.Combine(_environment.WebRootPath, "storages/apa_mc_1/TMD_EXCEL");

                        string filePathTotalMembersDeclaration_excel = Path.Combine(uploadPathTotalMembersDeclaration_excel,
                            fileNameTotalMembersDeclaration_excel + extensionTotalMembersDeclaration_excel);
                        //Using Buffering
                        using (var stream = System.IO.File.Create(filePathTotalMembersDeclaration_excel))
                        {
                            // The file is saved in a buffer before being processed
                            await TotalMembersDeclaration_excel.CopyToAsync(stream);
                        }
                        // Define the upload folder
                        string uploadPathEvidenceofPlanApprovalResolution = Path.Combine(_environment.WebRootPath, "storages/apa_mc_1/EPAR");
                        // Generate the file path
                        string filePathEvidenceofPlanApprovalResolution = Path.Combine(uploadPathEvidenceofPlanApprovalResolution,
                            fileNameEvidenceofPlanApprovalResolution + extensionEvidenceofPlanApprovalResolution);
                        //Using Buffering
                        using (var stream = System.IO.File.Create(filePathEvidenceofPlanApprovalResolution))
                        {
                            // The file is saved in a buffer before being processed
                            await EvidenceofPlanApprovalResolution.CopyToAsync(stream);
                        }
                        try
                        {
                            //Data Upload in Database
                            data.GPCode = result.GPCode;
                            data.FYCode = result.FYCode;
                            data.EvidenceofPlanApprovalResolution = fileNameEvidenceofPlanApprovalResolution + extensionEvidenceofPlanApprovalResolution;
                            data.EvidenceofPlanApprovalResolution_path = filePathEvidenceofPlanApprovalResolution;
                            data.TotalMembersDeclaration_excel = fileNameTotalMembersDeclaration_excel + extensionTotalMembersDeclaration_excel;
                            data.TotalMembersDeclaration_excel_path = filePathTotalMembersDeclaration_excel;
                            data.TotalMembersDeclaration_pdf = fileNameTotalMembersDeclaration_pdf + extensionTotalMembersDeclaration_pdf;
                            data.TotalMembersDeclaration_pdf_path = filePathTotalMembersDeclaration_pdf;
                            data.TotalNoofMember = result.TotalNoofMember;
                            data.NoofMemberAttended = result.NoofMemberAttended;
                            data.PlanApprovalDate = result.PlanApprovalDate;
                            data.SingleAgendaMeeting = result.SingleAgendaMeeting;
                            data.ActiveStatus = 3;
                            data.User_Id = HttpContext.Session.GetString("UserInfo");
                            data.Entry_Time = DateTime.Now;
                            _context.SaveChanges();
                            TempData["Success"] = "Your Report Uploaded Successfully!";
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine(ex.Message);
                        }
                        return RedirectToAction("APA_MC_1_Report", "GPReport");
                        
                    }
                }
            }
            else
            {

Views/GPEditDashboard/APA_MC_1_Edit.cshtml
@model APATools.Models.A_APA_MC_1
@{
    ViewData["Title"] = "APA 2024-2025 MC_1";
}

<div class="page-title">
    <div class="title_left">
        <h3>Welcome to the Dashboard!</h3>
    </div>

    <div class="title_right">
        <div class="col-md-5 col-sm-5   form-group pull-right top_search">
            <div class="input-group">
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>
                    Home of <small>
                        @if (Context.Session.GetString("UserInfo") != null)
                            @Context.Session.GetString("UserInfo")
                        
                            -
                        </small>
                    </h2>
                    <div class="clearfix"></div>
                </div>
                @if (TempData["Failed"] != null)
                {
                    <div class="x_content">
                        <div class="alert alert-danger">
                            @TempData["Failed"]
                        </div>
                    </div>
                }
            @if (TempData["Success"] != null)
            {
                <div class="x_content">
                    <div class="alert alert-success">
                        @TempData["Success"]
                    </div>
                </div>
            }
            <div class="x_content">
                <form asp-action="APA_MC_1_Edit" asp-asp-controller="GPEditDashboard" method="post" enctype="multipart/form-data">
                    @Html.AntiForgeryToken()
                    <div class="row">
                        <h4 class="col-form-label col-md-5 col-sm-5">APA-MC-1 Entry</h4>
                    </div>
                    <hr />
                    <div class="row">
                        <div class="item form-group col-md-6">
                            <label class="col-form-label col-md-5 col-sm-5 label-align" for="last-name">
                                GP Code <span class="required">*</span>
                            </label>
                            <div class="col-md-7 col-sm-7 ">
                                <input type="text" asp-for="GPCode" class="form-control col-form-label" readonly value="@Model.GPCode" />
                            </div>
                        </div>
                        <div class="item form-group col-md-6">
                            <label class="col-form-label col-md-5 col-sm-5 label-align" for="last-name">
                                Financial Year <span class="required">*</span>
                            </label>
                            <div class="col-md-7 col-sm-7 ">
                                <select asp-for="FYCode" class="form-control col-form-label" id="schemetype" required="required" readonly>
                                    <option selected value="@Model.FYCode">@ViewBag.FYName</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <hr />
                    <div class="row">
                        <div class="item form-group col-md-6">
                            <label class="col-form-label col-md-5 col-sm-5 label-align" for="last-name">
                                Total Number of GP Members (including EX-Officio) in 2024 - 2025 <span class="required">*</span>
                            </label>
                            <div class="col-md-7 col-sm-7 ">
                                <input asp-for="TotalNoofMember" id="totalNumber" type="number" class="form-control col-form-label" required />
                                <span>@Html.ValidationMessageFor(model => model.TotalNoofMember, "", new { @class = "text-danger" }) </span>
                            </div>
                        </div>
                        <div class="item form-group col-md-6">
                            <label class="col-form-label col-md-5 col-sm-5 label-align" for="last-name">
                                Number of GP Members (including EX-Officio) attended in Special General Body Meeting in 2024 - 2025 <span class="required">*</span>
                            </label>
                            <div class="col-md-7 col-sm-7 ">
                                <input asp-for="NoofMemberAttended" id="attendedNumber" class="form-control col-form-label" required type="number" />
                                <span>@Html.ValidationMessageFor(model => model.NoofMemberAttended, "", new { @class = "text-danger" }) </span>
                                <span id="error" style="color:red;"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="item form-group col-md-4">
                            <label class="col-form-label col-md-5 col-sm-5 label-align" for="last-name">
                                Plan Approval Resolution Doc (Max 5 MB in pdf) <span class="required">*</span>
                            </label>
                            <div class="col-md-7 col-sm-7 ">
                                <input type="file" asp-for="EvidenceofPlanApprovalResolution" class="form-control col-form-label" required />
                                <span>@Html.ValidationMessageFor(model => model.EvidenceofPlanApprovalResolution, "", new { @class = "text-danger" }) </span>
                            </div>
                        </div>
                        <div class="item form-group col-md-4">
                            <label class="col-form-label col-md-5 col-sm-5 label-align" for="last-name">
                                Total Member's Declaration (Max 5 MB in PDF)  <span class="required">*</span>
                            </label>
                            <div class="col-md-7 col-sm-7 ">
                                <input type="file" id="formFile" asp-for="TotalMembersDeclaration_pdf" class="form-control form-control-sm mb-3  col-form-label" required />
                                <span>@Html.ValidationMessageFor(model => model.TotalMembersDeclaration_pdf, "", new { @class = "text-danger" }) </span>
                            </div>
                        </div>
                        <div class="item form-group col-md-4">
                            <label class="col-form-label col-md-5 col-sm-5 label-align" for="last-name">
                                Total Member's Declaration (Max 5 MB in Excel)  <span class="required">*</span>
                            </label>
                            <div class="col-md-7 col-sm-7 ">
                                <input type="file" id="formFile" asp-for="TotalMembersDeclaration_excel" class="form-control form-control-sm mb-3  col-form-label" required />
                                <span>@Html.ValidationMessageFor(model => model.TotalMembersDeclaration_excel, "", new { @class = "text-danger" }) </span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="item form-group col-md-6">
                            <label class="col-form-label col-md-5 col-sm-5 label-align" for="last-name">
                                Plan Approval Date <span class="required">*</span>
                            </label>
                            <div class="col-md-7 col-sm-7 ">
                                <input type="date" asp-for="PlanApprovalDate" id="myDate" class="form-control col-form-label" required />
                                <span>@Html.ValidationMessageFor(model => model.PlanApprovalDate, "", new { @class = "text-danger" }) </span>
                            </div>
                        </div>
                        <div class="item form-group col-md-6">
                            <label class="col-form-label col-md-5 col-sm-5 label-align" for="last-name">
                                Single Agenda Meeting <span class="required">*</span>
                            </label>
                            <div class="col-md-7 col-sm-7 ">
                                <select asp-for="SingleAgendaMeeting" class="form-control col-form-label" required>
                                    <option value="">-- Select --</option>
                                    <option value="Yes">Yes</option>
                                    <option value="No">No</option>
                                </select>
                                <span>@Html.ValidationMessageFor(model => model.SingleAgendaMeeting, "", new { @class = "text-danger" }) </span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="item form-group col-md-6">
                            <label class="col-form-label col-md-5 col-sm-5 label-align" for="last-name">
                                <span class="required"></span>
                            </label>
                            <div class="col-md-7 col-sm-7 ">
                                <input type="submit" value="Submit" class="btn btn-primary col-form-label" />
                            </div>
                        </div>
                        <div class="item form-group col-md-6">
                            <label class="col-form-label col-md-5 col-sm-5 label-align" for="last-name">
                                <span class="required"></span>
                            </label>
                            <div class="col-md-7 col-sm-7 ">
                                <div class="row">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        function validateInputs() {
            var val1 = parseInt($('#totalNumber').val());
            var val2 = parseInt($('#attendedNumber').val());
            if (!isNaN(val1) && !isNaN(val2)) {
                if (val1 < val2) {
                    $('#error').text('Total Members is always greater than or equal to Attended Members');
                    //alert("Total Members is always greater than Attended Members");
                    $('#attendedNumber').val("");
                    //$('#attendedNumber').css("border-color","red");
                    //$('#attendedNumber').text("");
                    //
                    return false;
                } else {
                    $('#error').text('');
                    return true;
                }
            } else {
                $('#error').text('');
                return false;
            }
        }

        // Only trigger validation when input2 is typed into
        $('#attendedNumber').on('keyup', validateInputs);

        // Still check on form submit
            const today = new Date().toISOString().split('T')[0];
    document.getElementById("myDate").setAttribute('max', today);
    });
</script>

Views/GPEditDashboard/APA_MC_5_Edit.cshtml
@model APATools.Models.A_APA_MC_5
@{
    ViewBag.Title = "APA-MC-5&TE-11";
}

<div class="page-title">
    <div class="title_left">
        <h3>Welcome to the Entry of APA-MC-5</h3>
    </div>

    <div class="title_right">
        <div class="col-md-5 col-sm-5   form-group pull-right top_search">
            <div class="input-group">
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
            <div class="x_title">

                <h2>
                    GP Dashboard of @if (ViewBag.GPName != null)
                    {
                        <small>@ViewBag.GPName</small>
                    }
                </h2>
                <div class="clearfix"></div>
            </div>
            @if (TempData["Failed"] != null)
            {
                <div class="x_content">
                    <div class="alert alert-danger">
                        @TempData["Failed"]
                    </div>
                </div>
            }
            @if (TempData["Success"] != null)
            {
                <div class="x_content">
                    <div class="alert alert-success">
                        @TempData["Success"]
                    </div>
                </div>
            }
            <div class="x_content">
                <form asp-action="APA_MC_5_Edit" asp-controller="GPEditDashboard" method="post" enctype="multipart/form-data">

                    @Html.AntiForgeryToken()

                    <div class="row">
                        <h4 class="col-form-label col-md-5 col-sm-5">APA-MC-5 Entry</h4>
                    </div>
                    <hr />
                    <div class="row">
                        <div class="item form-group col-md-6">
                            <label class="col-form-label col-md-5 col-sm-5 label-align">
                                GP Code <span class="required">*</span>
                            </label>
                            <div class="col-md-7 col-sm-7 ">
                                <input type="number" class="form-control col-form-label" readonly value="@Model.GPCode" asp-for="GPCode" />
                            </div>
                        </div>
                        <div class="item form-group col-md-6">
                            <label class="col-form-label col-md-5 col-sm-5 label-align">
                                Financial Year <span class="required">*</span>
                            </label>
                            <div class="col-md-7 col-sm-7 ">
                                <select asp-for="FYCode" class="form-control col-form-label" id="finYear" required>
                                </select>
                                <span class="text-danger">@Model.FYCode</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="item form-group col-md-6">
                            <label class="col-form-label col-md-5 col-sm-5 label-align">
                                <span class="required">Audit Opinion</span>
                            </label>
                            <div class="col-md-7 col-sm-7 ">
                                <select asp-for="AuditOpinion" class="form-control col-form-label" required>
                                    <option value="">Select</option>
                                    <option value="Pass">Pass</option>
                                    <option value="Fail">Fail</option>
                                </select>
                                <span class="text-danger">@Model.AuditOpinion</span>
                            </div>
                        </div>
                        <div class="item form-group col-md-6">
                            <label class="col-form-label col-md-5 col-sm-5 label-align">
                                Audit Certificate / Entire Audit Report (Max 10 MB / .pdf format)<span class="required">*</span>
                            </label>
                            <div class="col-md-7 col-sm-7 ">
                                <input type="file" asp-for="AuditCertificate" class="form-control col-form-label" required />
                                <span>@Html.ValidationMessageFor(model => model.AuditCertificate, "", new { @class = "text-danger" }) </span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="item form-group col-md-6">
                            <label class="col-form-label col-md-5 col-sm-5 label-align">
                                <span class="required">*</span>
                            </label>
                            <div class="col-md-7 col-sm-7 ">
                                <input type="submit" class="btn btn-success" value="Submit" />
                            </div>
                        </div>

                        <div class="item form-group col-md-6">
                            <label class="col-form-label col-md-5 col-sm-5 label-align">
                                <span class="required"></span>
                            </label>
                            <div class="col-md-7 col-sm-7 ">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <hr />
                </form>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
<script type="text/javascript">
    $(function(){
        AjaxCall('@Url.Action("getFinacialYearforMC5", "GPDashboard")', null).done(function (response) {
            if (response.length > 0) {
                $('#finYear').html('');
                var options = '';
                options += '<option value="">Select Year</option>';
                for (var i = 0; i < response.length; i++) {
                    options += '<option value="' + response[i].fyCode + '">' + response[i].fyName + '</option>';
                }
                $('#finYear').append(options);

            }
        }).fail(function (error) {
            alert(error.StatusText);
        });
    });
    function AjaxCall(url, data, type) {
        return $.ajax({
            url: url,
            type: type ? type : 'GET',
            data: data,
            contentType: 'application/json'
        });
    }
    // Still check on form submit
            const today = new Date().toISOString().split('T')[0];
    document.getElementById("myDate").setAttribute('max', today);
    document.getElementById("myDate1").setAttribute('max', today);
    document.getElementById("myDate2").setAttribute('max', today);
</script>